name: Generate and Deploy Site

on:
  schedule:
    - cron: "0 */12 * * *" # Every 12 hours
  workflow_dispatch: # Allow manual runs

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up uv
        uses: astral-sh/setup-uv@v4

      - name: Install dependencies
        run: uv pip install --system -r dev-requirements.txt

      - name: Run gen.py
        run: python gen.py

      - uses: actions/setup-node@v6
        with:
          node-version: "lts/*"

      - name: Install markdown-to-html
        run: npm i -g markdown-to-html-cli

      - name: Transform markdown
        run: |
          markdown-to-html --source dist/index.md --output dist/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
