name: Generate Site

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: uv pip install --system -r dev-requirements.txt

      - name: Generate Markdown site
        run: python gen.py

      - name: Configure Jekyll
        run: |
          cat > site/_config.yml <<EOF
          title: My Site
          remote_theme: pages-themes/cayman@v0.2.0

          plugins:
            - jekyll-remote-theme
          EOF

      - name: Disable GitHub Actions cleanup
        run: touch site/.nojekyll.disabled

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
